### ISSUE TITLE
linux compile err

### ISSUE THREAD

**Issue by menggaoling** [nxp-imx/mfgtools#359]
1.base64_encode need declare like this to avoid compile err.std::string HttpStream::base64_encode(std::string str)(C++20);
2.
/usr/bin/ld: 找不到 -lOPENSSL_SSL_LIBRARY-NOTFOUND: 没有那个文件或目录
/usr/bin/ld: 找不到 -lOPENSSL_CRYPTO_LIBRARY-NOTFOUND: 没有那个文件或目录

solved!sudo apt-get install libssl-dev install openssl need redo cmake .

ubuntu 64bit 22.04

**Comment by nxpfrankli** [comment]
CI have not reported such error.  Did you install openssl-dev ?

**Comment by menggaoling** [comment]
yes,the second problem has been solved.Thanks for your attention.
