### ISSUE TITLE
UUU tool stucking while flashing imx-boot - Coral Dev Board(IMX8MQ)

### ISSUE THREAD

**Issue by alperak** [nxp-imx/mfgtools#378]
I'm trying to flash bootloader(imx-boot) and image(.wic, created with yocto) to EMMC with UUU tool but stucking after wrote "imx-boot".

UUU and u-boot output: pastebin.com/1BFrTJvQ
also, u-boot config: pastebin.com/snxCVxA1

**Comment by nxpfrankli** [comment]
Sorry, nxp block pastebin.com access. Can you parse your result in github issue?

**Comment by alperak** [comment]
[uboot_defconfig.txt](https://github.com/nxp-imx/mfgtools/files/11828801/uboot_defconfig.txt)
[serial_debug_output.txt](https://github.com/nxp-imx/mfgtools/files/11828802/serial_debug_output.txt)
[emmc_all_output.txt](https://github.com/nxp-imx/mfgtools/files/11828803/emmc_all_output.txt)
[uuu_lsusb_output.txt](https://github.com/nxp-imx/mfgtools/files/11828804/uuu_lsusb_output.txt)

**Comment by nxpfrankli** [comment]
Your uboot may too old. 

The method of "Back to ROM, SDP" already not used.  we already change to using SPL SDP HID download. You can refer our release uboot.
