### ISSUE TITLE
Not found: install_linux_fw_uuu.sh

### ISSUE THREAD

**Issue by weyselgulec** [nxp-imx/mfgtools#441]
Hallo everybody, 

1. I am beginner with DIGI MP15 Hardware Kit and I have a Lunix OS. 
I have done every steps that this links tells me:
https://www.digi.com/resources/documentation/digidocs/embedded/dey/4.0/ccmp15/yocto-gs-program-fw_t.html
but there is a problem which i cant find this file :install_linux_fw_uuu.sh
Thats why i cant use this device? Any idea ?

**Comment by gruizdigi** [comment]
Hi @weyselgulec ,

For Digi product and firmware questions please open a comment in the following repository: https://github.com/digi-embedded/meta-digi

**Comment by nxpfrankli** [comment]
handle by other place
